- name: get mysql db password
  shell: 'kubectl get secret --namespace database mysql -o jsonpath="{.data.mysql-root-password}" | base64 -d'
  register: mysql_db_password_raw
  when: inventory_hostname in groups[group][0]

- name: set fact join command
  set_fact:
    mysql_db_password : "{{ mysql_db_password_raw.stdout }}"
  when: inventory_hostname in groups[group][0]

- name: DB Pre Setup for Jenkins Server
  script: files/pre-setup.sh {{ db_namespace }}
  when: inventory_hostname in groups[group]

- name: Setup Jenkins Cluster
  script: files/setup.sh {{ domain }} {{ item.secret_name }} {{ namespace }} {{ mysql_db_password }}
  when: inventory_hostname in groups[group] and ( tls is defined)
  loop: "{{ tls }}"
